name: Wiki

on: gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2

      - name: Slack Notification
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          SENDER: ${{ github.event.sender.login }}
          COLOR: ${{ github.event.pages[0].action == 'created' && '#58a359' || '#1a60b0' }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          url=${HTML_URL}/_compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)
          curl -X POST ${WEBHOOK_URL} \
               -H 'Content-type: application/json' \
               -d "{ \
                    \"attachments\": [{ \
                      \"color\": \"${COLOR}\", \
                      \"blocks\": [{ \
                        \"type\": \"section\", \
                        \"text\":{ \
                          \"type\": \"mrkdwn\", \
                          \"text\": \"Wiki ${ACTION}: ${TITLE} by ${SENDER}\n${url}\" \
                        } \
                      }] \
                    }] \
                  }"
