name: Wiki

on: gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2

      - name: Slack Notification
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SUMMARY: ${{ github.event.pages[0].summary }}
          SENDER: ${{ github.event.sender }}
        run: |
          url=${HTML_URL}/_compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"Wiki ${ACTION}: ${TITLE}\n${url}\n${SUMMARY}\n${SENDER}\"}" \
            ${WEBHOOK_URL}
